title: Minimal theme
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal


#Layout
show_social: true      #show site description and social links in the footer
show_excerpts: true    #show article excerpts on the home page 
show_frame: true       #adds a gray frame to the site
show sidebar: false     #show a sidebar instead of the usual header

#Menu

navigation:
  - file: "/cv.pdf"
    title: "CV"
    icon: "home"
  - title: "Blog"
    file: "/blog.md"

external:               # see http://fontawesome.com/icons

- {title: Mail, icon: envelope, url: "mailto:niklasbuschmann@users.noreply.github.com"} 
- {title: Github, icon: github, url: "https://github.com/niklasbuschmann/contrast"} 
- {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#disqus_shortname:""  # see https://disqus.com/
#isso_domain:""       # see https://posativ.org/isso/

plugins:
- jekyll-feed

